[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000


[fmt]
line_length = 160
tab_width = 4
bracket_spacing = true
int_types = 'long'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[fuzz]
runs = 1024